language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Build
  - docker-compose -f docker-compose-build.yaml build --parallel
# Tagging
  - docker tag udagram-api-feed  medgov/udagram-api-feed:v1
  - docker tag udagram-api-user  medgov/udagram-api-user:v1
  - docker tag udagram-frontend  medgov/udagram-frontend:v1
  - docker tag reverseproxy  medgov/reverseproxy:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push medgov/udagram-api-feed:v1
  - docker push medgov/udagram-api-user:v1
  - docker push medgov/udagram-frontend:v1
  - docker push medgov/reverseproxy  20med/reverseproxy:v1